---
- name: my super playbook for variables lesson
  hosts: all
  become: true

  vars:
    message1: Hello
    message2: World
    secret: asdfjkl;

  tasks:
  - name: Print secret variable
    debug: 
      var: secret

  - debug:
      msg: "secret word: {{ secret }}"

  - debug:
      msg: "Owner of this server is {{ owner }}"

  - set_fact: full_message="{{ message1 }} {{ message2 }} from {{ owner }}"

  - debug:
      var: full_message