---
- name: install nginx and upload my web-page
  hosts: all
  become: true

  vars:
    source_file: ./site/index.html
    dest_file: /var/www/html
    dest_file_rhel: /usr/share/nginx/html

  tasks:
  - name: Check Linux family
    debug: var = ansible_os_family