---
- name: Error Handling
  hosts: all
  become: true

  tasks:
  - name: task 1
    package: name=nanaooaon state=latest
    ignore_errors: true

  - name: task 2
    shell: ls -la /etc
    register: results

  - debug:
      var: results

  - name: task3 
    shell: echo Wake up, Neo...