---
- name: test connection to my servers
  hosts: all
  become: yes

  tasks:

    # data: Data to return for the `ping' return value. If 
    - name: ping my servers
      ping:
       data: "#"
       become: true 
       become_method: su 
       become_user: nobody 
       become_flags: "-s /bin/sh" 
       when: variable is defined 
       with_items: array 
      
      