---
- name: My Playbook
  hosts: all
  become: true

  vars: 
    mytext: "Hello, User!"

  tasks:
  - name: Ping
    ping:

  - name: Unregister server from load balancer
    shell: echo This server is {{ inventory_hostname }} was unregistered from load balancer, node name is {{ ansible_nodename }} >> /home/log.txt
    delegate_to: 127.0.0.1

  - name: Create file1
    copy:
      dest: /home/file1.txt
      content:
        This is file1
        Hello World
        {{ mytext }}
    delegate_to: linux3

  - name: Create file2
    copy:
      dest: /home/file2.txt
      content:
        This is file2
        Hello World
        {{ mytext }}
    delegate_to: linux3

  - name: Reboot my servers
    shell: sleep 3 && reboot now
    async: 1
    poll: 0

  - name: Wait until my servers will come up online
    wait_for: 
      host: "{{ inventory_hostname }}"
      state: started
      delay: 5
      timeout: 40
    delegate_to: 127.0.0.1