---
- name: Loops Playbook
  hosts: linux3
  become: 

  tasks:
  - name: Say Hello to ALL
    debug: msg="Hello {{ item }}"
    loop:
      - "User1"
      - "User2"
      - "User3"
      - "User4"

  - name: Loop Until
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: output
    delay: 2
    retries: 10
    until: output.stdout.find("ZZZZZZZ") == false

  - name: Print Final output
    debug:
      var: output.stdout