---
- name: remove nginx and delete my web-page
  hosts: all
  become: true

  vars:
    source_file: ./site/index.html
    dest_file: /var/www/html/*

  tasks:
  - name: remove nginx web-server
    package: name=nginx state=absent

  - name: delete site from servers
    shell: "rm -rf {{ dest_file }}"

  - block
    - name: Remove Nginx and site from Debian systems
      package: name=nginx state=absent

    - name: Delete site files form folder
      shell: 