---
- name: install default nginx web server
  hosts: all
  become: 

  tasks:
  - name: install nginx web server
    apt: name=nginx state=latest
      

  - name: start nginx on boot
    service: name=nginx state=started enable=true
    